/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ScoreboardIndexRouteImport } from './routes/scoreboard.index'
import { Route as ScoreboardWarzoneRouteImport } from './routes/scoreboard.warzone'
import { Route as AuthenticatedAdminScoreboardRouteImport } from './routes/_authenticated/admin.scoreboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardIndexRoute = ScoreboardIndexRouteImport.update({
  id: '/scoreboard/',
  path: '/scoreboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardWarzoneRoute = ScoreboardWarzoneRouteImport.update({
  id: '/scoreboard/warzone',
  path: '/scoreboard/warzone',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminScoreboardRoute =
  AuthenticatedAdminScoreboardRouteImport.update({
    id: '/admin/scoreboard',
    path: '/admin/scoreboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/register': typeof RegisterRoute
  '/scoreboard/warzone': typeof ScoreboardWarzoneRoute
  '/scoreboard/': typeof ScoreboardIndexRoute
  '/admin/scoreboard': typeof AuthenticatedAdminScoreboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/register': typeof RegisterRoute
  '/scoreboard/warzone': typeof ScoreboardWarzoneRoute
  '/scoreboard': typeof ScoreboardIndexRoute
  '/admin/scoreboard': typeof AuthenticatedAdminScoreboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/register': typeof RegisterRoute
  '/scoreboard/warzone': typeof ScoreboardWarzoneRoute
  '/scoreboard/': typeof ScoreboardIndexRoute
  '/_authenticated/admin/scoreboard': typeof AuthenticatedAdminScoreboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/leaderboard'
    | '/register'
    | '/scoreboard/warzone'
    | '/scoreboard/'
    | '/admin/scoreboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/leaderboard'
    | '/register'
    | '/scoreboard/warzone'
    | '/scoreboard'
    | '/admin/scoreboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/leaderboard'
    | '/register'
    | '/scoreboard/warzone'
    | '/scoreboard/'
    | '/_authenticated/admin/scoreboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  RegisterRoute: typeof RegisterRoute
  ScoreboardWarzoneRoute: typeof ScoreboardWarzoneRoute
  ScoreboardIndexRoute: typeof ScoreboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard/': {
      id: '/scoreboard/'
      path: '/scoreboard'
      fullPath: '/scoreboard/'
      preLoaderRoute: typeof ScoreboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard/warzone': {
      id: '/scoreboard/warzone'
      path: '/scoreboard/warzone'
      fullPath: '/scoreboard/warzone'
      preLoaderRoute: typeof ScoreboardWarzoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/scoreboard': {
      id: '/_authenticated/admin/scoreboard'
      path: '/admin/scoreboard'
      fullPath: '/admin/scoreboard'
      preLoaderRoute: typeof AuthenticatedAdminScoreboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminScoreboardRoute: typeof AuthenticatedAdminScoreboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminScoreboardRoute: AuthenticatedAdminScoreboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  RegisterRoute: RegisterRoute,
  ScoreboardWarzoneRoute: ScoreboardWarzoneRoute,
  ScoreboardIndexRoute: ScoreboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
